# Generated by Django 4.1.3 on 2024-01-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acct',
            name='account_num',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='acct',
            name='currency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='acct',
            name='suspense',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='intermidiary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='message_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='nostro_account',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='qm_processed',
            field=models.CharField(default='pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='senders_ref',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='suspense',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='team',
            field=models.CharField(blank=True, max_length=130),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='value_date',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='unmatchedtransaction',
            name='message_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='unmatchedtransaction',
            name='nostro_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='unmatchedtransaction',
            name='qm_processed',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='unmatchedtransaction',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='unmatchedtransaction',
            name='suspense',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='unmatchedtransaction',
            name='team',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='unmatchedtransaction',
            name='value_date',
            field=models.CharField(max_length=50),
        ),
    ]
