# Generated by Django 4.1.3 on 2024-01-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0002_alter_acct_account_num_alter_acct_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unmatchedtransaction',
            name='ordering_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
